services:
  app-1:
    build:
      context: .
    ports:
      - 8081:8080
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=payment
      - DB_USER=user
      - DB_PASSWORD=123456
      - REDIS_URL=redis://redis:6379
      - WORKERS=2
    volumes:
      - ./src:/usr/local/app/src
    command: bun run --watch /usr/local/app/src/main.ts
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network
      - payment-processor

  redis:
    image: redis:7.2
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - backend-network
        
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: payment 
      POSTGRES_USER: user    
      POSTGRES_PASSWORD: 123456 
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "payment"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  nginx:
    image: nginx:1.24.0
    ports:
      - "9999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-1
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80" 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  db-data:

networks:
  payment-processor:
    external: true
  backend-network:
    driver: bridge
