services:
  app-1: &app-1
    build:
      context: .
    ports:
      - 8081:8080
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    volumes:
      - type: bind
        source: ./src
        target: /usr/loca/app/src/
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/local/app/src/
        - path: ./src/package.json
          action: rebuild
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-network
      - payment-processor

  app-2:
    <<: *app-1
    ports:
      - 8082:8080
        
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  nginx:
    image: nginx:1.24.0
    ports:
      - "9999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-1
      - app-2
    networks:
      - backend-network

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt

networks:
  payment-processor:
    external: true
  backend-network:
    driver: bridge
